import { PageTag } from '@/components/ui/PageTag'
import type {
  GrammarCefrLevel,
  GrammarComplexity,
  GrammarIeltsImpact,
  GrammarL1Risk,
} from '@/modules/grammar/types'

/**
 * The two-axis display. `cefrLevel` says when a learner meets a rule;
 * `complexity` says how hard it is to get right. They are shown side by side
 * on purpose, because they diverge: articles are A1 / difficulty 5, future
 * perfect continuous is C1 / difficulty 3.
 */
export function GrammarAxes({
  cefrLevel,
  complexity,
  ieltsImpact,
  l1Risk,
}: {
  cefrLevel: GrammarCefrLevel
  complexity: GrammarComplexity
  ieltsImpact?: GrammarIeltsImpact
  l1Risk: GrammarL1Risk
}) {
  return (
    <div className="flex flex-wrap items-center gap-2">
      <PageTag tone="pale">{cefrLevel}</PageTag>
      <span className="border-manga-black bg-manga-white text-manga-black border-2 px-2 py-0.5 font-sans text-xs font-black uppercase">
        Difficulty {complexity}/5
      </span>
      <L1RiskTag l1Risk={l1Risk} />
      {ieltsImpact ? (
        <span
          className="border-manga-black text-manga-black border-2 border-dashed px-2 py-0.5 font-sans text-xs font-black uppercase"
          title="Derived from difficulty and family, not hand-assigned"
        >
          IELTS {ieltsImpact}
        </span>
      ) : null}
    </div>
  )
}

const L1_RISK_LABEL: Record<GrammarL1Risk, string> = {
  high: 'VI risk high',
  low: 'VI risk low',
  medium: 'VI risk medium',
}

/**
 * Vietnamese L1 transfer risk. This is the axis no off-the-shelf grammar course
 * can offer, so it gets the loudest treatment when it is high.
 */
export function L1RiskTag({ l1Risk }: { l1Risk: GrammarL1Risk }) {
  const emphasis =
    l1Risk === 'high'
      ? 'bg-manga-red text-manga-white'
      : 'bg-manga-white text-manga-black'

  return (
    <span
      className={`border-manga-black border-2 px-2 py-0.5 font-sans text-xs font-black uppercase ${emphasis}`}
      title="How much Vietnamese as a first language interferes with this point"
    >
      {L1_RISK_LABEL[l1Risk]}
    </span>
  )
}

/**
 * Shown on any lesson whose body has not been human-reviewed.
 *
 * This banner is the entire reason `reviewStatus` exists. The lessons are
 * bulk-generated by a model, and a confidently-worded wrong grammar rule is
 * worse than no rule at all - so the learner is never left guessing whether a
 * human has checked what they are reading.
 */
export function UnverifiedBanner() {
  return (
    <div
      className="border-manga-black bg-manga-red text-manga-white border-3 p-3 shadow-[4px_4px_0_var(--manga-black)]"
      role="status"
    >
      <p className="font-sans text-sm leading-6 font-black uppercase">
        Unverified lesson
      </p>
      <p className="mt-1 text-sm leading-6 font-semibold">
        This explanation was generated and has not been checked by a human yet.
        Treat the edge cases with suspicion, and mark it reviewed in admin once
        you have read it properly.
      </p>
    </div>
  )
}
